UI.Web/Models/MateriaViewModel.cs
using System.Collections.Generic;

namespace UI.Web.Models
{
    public class MateriaViewModel
    {
        public string PlanDescripcion { get; set; }

        public List<MateriaModel> Materias { get; set; }
    }
}

UI.Web/Controllers/MateriaController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using AutoMapper;
using Business.Entities;
using Business.Logic;
using Business.Util.Exceptions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using UI.Web.Models;

namespace UI.Web.Controllers
{
    [ResponseCache(NoStore = true, Duration = 0)]
    public class MateriaController : Controller
    {
        private IMapper mapper;
        private readonly INotyfService notyf;

        private MateriaLogic MateriaLogic => new();

        private PlanLogic PlanLogic => new();

        public MateriaController(IMapper mapper, INotyfService notyf)
        {
            this.mapper = mapper;
            this.notyf = notyf;
        }


        [Authorize(Policy = "Materias.Consulta")]
        public IActionResult Index(int id)
        {
            var plan = PlanLogic.GetOne(id);
            var model = mapper.Map<PlanViewModel>(plan);
            return View(model);
        }

        [Authorize(Policy = "Materias.Alta")]
        public IActionResult Nuevo(int id)
        {
            var plan = PlanLogic.GetOne(id);
            var model = new MateriaModel()
            {
                PlanDescripcion = plan.Descripcion,
                PlanId = plan.Id
            };
            return View(model);
        }

        [Authorize(Policy = "Materias.Modificacion")]
        public IActionResult Editar(int id)
        {
            var mat = this.MateriaLogic.GetOne(id);
            var model = mapper.Map<MateriaModel>(mat);
            return View(model);
        }

        [HttpPost]
        [Authorize(Policy = "Materias.Modificacion")]
        public IActionResult Editar(MateriaModel model) 
        {
            if (ModelState.IsValid)
            {
                var materia = mapper.Map<Materia>(model);
                this.MateriaLogic.Guardar(materia);
                this.notyf.Success("Se han guardado los cambios de la materia");
                return RedirectToAction("Index", new { id = materia.PlanId });
            }
            return View(model);
        }

        [HttpPost]
        [Authorize(Policy = "Materias.Alta")]
        public IActionResult Nuevo(MateriaModel model)
        {
            if (ModelState.IsValid)
            {
                var materia = mapper.Map<Materia>(model);
                this.MateriaLogic.Guardar(materia);
                this.notyf.Success("Se ha creado la materia: " + materia.Descripcion);
                return RedirectToAction("Index", new { id = materia.PlanId });
            }
            return View(model);
        }

        [Authorize(Policy = "Materias.Baja")]
        public IActionResult Borrar(int id)
        {
            var materia = this.MateriaLogic.GetOne(id);
            var model = this.mapper.Map<MateriaModel>(materia);
            return View(model);
        }

        [HttpPost]
        [Authorize(Policy = "Materias.Baja")]
        public IActionResult Borrar(MateriaModel materia)
        {
            try
            {
                var mat = this.MateriaLogic.GetOne(materia.Id);
                this.MateriaLogic.Borrar(materia.Id);
                this.notyf.Success("Se ha borrado la materia: " + mat.Descripcion);
                return RedirectToAction("Index", new { id = mat.PlanId });
            }
            catch (DeleteCFReferenciadaException ex)
            {
                TempData["Error"] = ex.Message;
                return RedirectToAction("Borrar", new { id = materia.Id });
            }
        }

        [HttpPost]
        public JsonResult Lista(int id)
        {
            var entities = mapper.Map<List<MateriaModel>>(MateriaLogic.GetAllByPlan(id));
            return Json(entities);
        }
    }
}

UI.Web/Controllers/PlanController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using AutoMapper;
using Business.Entities;
using Business.Logic;
using Business.Util.Exceptions;
using FastReport;
using FastReport.Export.PdfSimple;
using FastReport.Web;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using UI.Web.Models;

namespace UI.Web.Controllers
{


    [Authorize]
    [ResponseCache(NoStore = true, Duration = 0)]
    public class PlanController : Controller
    {
        private readonly IMapper mapper;
        private readonly IWebHostEnvironment webHostEnviroment;
        private readonly INotyfService notyf;

        private PlanLogic PlanLogic => new();

        private EspecialidadLogic EspecialidadLogic => new();

        public PlanController(IMapper mapper, IWebHostEnvironment webHostEnvironment, INotyfService notyf)
        {
            this.mapper = mapper;
            this.webHostEnviroment = webHostEnvironment;
            this.notyf = notyf;
        }



        // GET: PlanController
        [Authorize(Policy = "Planes.Consulta")]
        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                var claims = User.Claims;
            }
            var vms = mapper.Map<List<PlanViewModel>>(PlanLogic.GetAll());
            return View(vms);
        }



        // GET: PlanController/Create
        [Authorize(Policy = "Planes.Alta")]
        public ActionResult Nuevo()
        {
            var vm = new PlanViewModel();
            vm.Especialidades = mapper.Map<List<EspecialidadViewModel>>(EspecialidadLogic.GetAll());


            vm.Materias = new();
            vm.Materia = new();
            return View(vm);
        }

        // POST: PlanController/Create
        [Authorize(Policy = "Planes.Alta")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Guardar(PlanViewModel planViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var entity = mapper.Map<Plan>(planViewModel);
                    PlanLogic.Save(entity);
                    notyf.Success("Se ha agregado un nuevo plan", 3);
                    return RedirectToAction(nameof(Index));
                }
                return View(planViewModel);
            }
            catch(Exception ex)
            {
                return View();
            }
        }

        // GET: PlanController/Edit/5
        [Authorize(Policy = "Planes.Modificacion")]
        public ActionResult Editar(int id)
        {
            var plan = this.PlanLogic.GetOne(id);
            var vm = new PlanViewModel();
            vm.Id = plan.Id;
            vm.Descripcion = plan.Descripcion;
            vm.EspecialidadId = plan.EspecialidadId;
            vm.Especialidades = mapper.Map<List<EspecialidadViewModel>>(EspecialidadLogic.GetAll());
            vm.Materias = new();
            vm.Materia = new();
            return View(vm);
        }


        [HttpPost]
        [Authorize(Policy = "Planes.Alta")]
        [ValidateAntiForgeryToken]
        public ActionResult Nuevo(PlanViewModel planViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var entity = mapper.Map<Plan>(planViewModel);
                    PlanLogic.Save(entity);
                    notyf.Success($"Se ha creado el plan {entity.Descripcion}", 3);
                    return RedirectToAction(nameof(Index));
                }
                return View(planViewModel);
            }
            catch (Exception ex)
            {
                return View();
            }
        }


        [HttpPost]
        [Authorize(Policy = "Planes.Modificacion")]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(PlanViewModel planViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var entity = mapper.Map<Plan>(planViewModel);
                    PlanLogic.Save(entity);
                    notyf.Success("Se han guardado los cambios plan", 3);
                    return RedirectToAction(nameof(Index));
                }
                return View(planViewModel);
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        // GET: PlanController/Delete/5
        [Authorize(Policy = "Planes.Baja")]
        public ActionResult Borrar(int id)
        {
            var plan = this.PlanLogic.GetOne(id);
            var vm = new PlanViewModel();
            vm.Id = plan.Id;
            vm.Descripcion = plan.Descripcion;
            vm.EspecialidadId = plan.EspecialidadId;
            vm.EspecialidadDescripcion = plan.Especialidad.Descripcion;
            return View(vm);
        }

        // POST: PlanController/Delete/5
        [HttpPost]
        [Authorize(Policy = "Planes.Baja")]
        [ValidateAntiForgeryToken]
        public ActionResult Borrar(PlanViewModel model)
        {
            try
            {
                PlanLogic.Delete(model.Id);
                notyf.Success("Se ha borrado el plan", 3);
                return RedirectToAction(nameof(Index));
            }
            catch(DeleteCFReferenciadaException ex)
            {
                TempData["Error"] = ex.Message;
                return RedirectToAction("Borrar", new { id = model.Id });
            }
        }

        [HttpPost]
        [Authorize]
        public JsonResult PlanesByEspecialidad(int id)
        {
            var results = PlanLogic.PlanesByEspecialidad(id);
            return Json(results);
        }


        [HttpGet]
        [Authorize]
        public JsonResult GetPlanes()
        {
            var results = this.mapper.Map<List<PlanViewModel>>(PlanLogic.GetAll());
            return Json(results);
        }

        [Authorize]
        public IActionResult Reporte(int id)
        {

            var plan = PlanLogic.GetOne(id);
            var rep = new ReportePlan();
            rep.Especialidad = plan.Especialidad.Descripcion;
            rep.Plan = plan.Descripcion;
            foreach (var item in plan.Materias)
            {
                var materia = new ReportePlan.Materia() { Descripcion = item.Descripcion, HorasSemanales = item.HSSemanales, HorasTotales = item.HSTotales };
                rep.Materias.Add(materia);
            }
            rep.Prepare();
            Stream stream = new MemoryStream();
            rep.Report.Export(new PDFSimpleExport(), stream);
            stream.Position = 0;
            return File(stream, "application/pdf", $"{plan.Descripcion}.pdf");

        }
    }
}

UI.Web/Views/Materia/Borrar.cshtml
@model UI.Web.Models.MateriaModel

@{
    ViewData["Title"] = "Borrar";
}

@if (TempData.ContainsKey("Error"))
{
    <div class="alert alert-danger" role="alert">
        @TempData["Error"]
    </div>
}
                <div class="card bg-secondary p-2">
    <h1 class="text-center">Borrar Materia</h1>

    <h3 class="text-center">¿Esta seguro de borrar la siguiente materia?:</h3>
    <div class="row">
        
        <form asp-action="Borrar">

            <div class="row">
                <div class="col-md-4 col-12 col-lg-6 mx-auto">

                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="mb-3">
                                <dt class="col-sm-2">
                                    @Html.DisplayNameFor(model => model.Descripcion)
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.Descripcion)
                                </dd>
                                <dt class="col-sm-2">
                                    @Html.DisplayNameFor(model => model.HSSemanales)
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.HSSemanales)
                                </dd>
                                <dt class="col-sm-2">
                                    @Html.DisplayNameFor(model => model.HSTotales)
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.HSTotales)
                                </dd>
                        </div>
                        <div class="row">
                            <div class="col-md-6 col-lg-6">
                            <input type="submit" value="Borrar" class="btn btn-success w-100 mb-3" />
                            </div>
                            <div class="col-md-6 col-lg-6">
                            <a asp-action="Index" asp-route-id="@Model.PlanId" class="btn btn-primary btn btn-danger w-100 mb-3">Cancelar</a>
                            </div>

                        </div>
      
                </div>
            </div>
  
        </form>
        

</div>
</div

UI.Web/Views/Materia/Editar.cshtml
@model MateriaModel
<h3 class="display-6 text-center">Editar materia - @Model.PlanDescripcion</h3>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-6 col-12 pb-3 pb-md-0  mx-auto">
            <partial for="@Model" name="_formularioMateria" />
        </div>
    </div>
</div>

UI.Web/Views/Materia/Index.cshtml
@model PlanViewModel

@{
    ViewData["Title"] = "Index";
}

<h2 class="text-center">Materias del plan: @Model.Descripcion</h2>
<div class="container">
    <div class="row">
        <div class="col-md-12 text-center text-md-left p-2">
            <a asp-controller="Materia" asp-action="Nuevo" asp-route-id="@Model.Id" class="btn btn-primary">Crear Materia</a>
            <a asp-controller="Plan" asp-action="Index"  class="btn btn-secondary">Volver a planes</a>
        </div>
    </div>
</div>

<div class="container-fluid">
    <table id="table" class="display responsive nowrap table table-striped" style="width:100%">
        <thead>
            <tr>
                <th class="text-left">
                    @Html.DisplayNameFor(model => model.Descripcion)
                </th>
                <th class="text-center">Acciones</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Materias)
            {
                <tr>
                    <td class="text-left">
                        @Html.DisplayFor(modelItem => item.Descripcion)
                    </td>
                    <td class="text-center">
                        <a class="btn btn-primary btn-sm" title="Editar materia" asp-action="Editar" asp-route-id="@item.Id"><i class="fa fa-pencil fa-sm" aria-hidden="true"></i> Editar</a>
                        <a class="btn btn-danger btn-sm" title="Borrar borrar" asp-action="Borrar" asp-route-id="@item.Id"><i class="fa fa-trash fa-sm" aria-hidden="true"></i> Borrar</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

@section scripts {
    <script>
        $(document).ready(function () {
            let table = new DataTable('#table', {
                language: {
                    "emptyTable": "No existen materias registrados en el plan",
                    "search": "Buscar: ",
                    "zeroRecords": "No se han encontrado especialidades en la búsqueda",
                    "paginate": {
                        "first": "Primero",
                        "last": "Último",
                        "next": "Siguiente",
                        "previous": "Anterior"
                    }
                },
                responsive: true,
                pageLength:8,
                lengthChange: false,
                info: false,
            });
        });
    </script>
}

UI.Web/Views/Materia/Nuevo.cshtml
@model MateriaModel
<h3 class="display-6 text-center">Nueva materia - @Model.PlanDescripcion</h3>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-6 col-12 pb-3 pb-md-0  mx-auto">
            <partial for="@Model" name="_formularioMateria" />
        </div>
    </div>
</div>

UI.Web/Views/Materia/_formularioMateria.cshtml
@model MateriaModel
@{
    var accion = Model.Id == 0 ? "Nuevo" : "Editar";
}

<div class="row">
    <div class="col-md-10 col-12 col-lg-10 mx-auto">
        <form id="form" asp-action="@accion">
            <input asp-for="Id" value="@Model.Id" hidden />
            <input asp-for="PlanId" hidden />
            <input asp-for="PlanDescripcion" hidden />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="mb-3">
                <label asp-for="Descripcion" class="form-label col-form-label-lg"></label>
                <input asp-for="Descripcion" class="form-control form-control-md" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="HSSemanales" class="form-label col-form-label-lg"></label>
                <input asp-for="HSSemanales" type="number" class="form-control form-control-md" />
                <span asp-validation-for="HSSemanales" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="HSTotales" class="form-label col-form-label-lg"></label>
                <input asp-for="HSTotales" type="number" class="form-control form-control-md" />
                <span asp-validation-for="HSTotales" class="text-danger"></span>
            </div>
            <div class="row">
                <div class="col-md-6 col-lg-6">
                    <input type="submit" value="Guardar" class="btn btn-success w-100 mb-3" />
                </div>
                <div class="col-md-6 col-lg-6">
                    <a asp-action="Index" asp-route-id="@Model.PlanId" class="btn btn-danger w-100 mb-3">Cancelar</a>
                </div>

            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

}