UI.Web/Models/AlumnoInscripcionViewModel.cs
using Business.Entities;
using Business.Util;

namespace UI.Web.Models
{
    public class AlumnoInscripcionViewModel
    {
        public int Id { get; set; }
        public string Condicion { get; set; }
        public int? Nota { get; set; }
        public int AlumnoId { get; set; }
        public int CursoId { get; set; }
        public PersonaViewModel Alumno { get; set; }
        public CursoViewModel Curso { get; set; }
        public string Plan { get; set; }
        public CondicionEnum CondicionEnum { get; set; }
    }
}

UI.Web/Controllers/AlumnoInscripcionController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using AspNetCoreHero.ToastNotification.Notyf;
using AutoMapper;
using Business.Entities;
using Business.Logic;
using Business.Util;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using UI.Web.Models;

namespace UI.Web.Controllers
{
    [Authorize]
    [ResponseCache(NoStore = true, Duration = 0)]
    public class AlumnoInscripcionController : Controller
    {
        private readonly IMapper mapper;
        private readonly INotyfService notyf;
        private readonly AlumnoInscripcionLogic alumnoInscripcionLogic;
        private readonly PersonaLogic personaLogic;

        public AlumnoInscripcionController(IMapper mapper, INotyfService notyf)
        {
            this.mapper = mapper;
            this.notyf = notyf;
            this.alumnoInscripcionLogic = new();
            this.personaLogic = new();
        }

        // GET: AlumnoInscripcionController
        public ActionResult Inscripciones(int id)
        {
            var inscripciones = this.alumnoInscripcionLogic.GetAllByAlumno(id);
            var models = this.mapper.Map<List<AlumnoInscripcionViewModel>>(inscripciones);
            var model = new AlumnoInscripcionHeadViewModel() { AlumnoInscripciones = models, AlumnoId = id };
            return View(model);
        }



        // GET: AlumnoInscripcionController/Create
        public ActionResult NuevaInscripcion(int idAlumno)
        {
            var alumno = this.personaLogic.GetOne(idAlumno);
            var alumnoModel = new PersonaViewModel() { Id = alumno.Id, Apellido = alumno.Apellido, Nombre = alumno.Nombre, PlanId = alumno.PlanId, Legajo = alumno.Legajo };

            var model = new AlumnoInscripcionViewModel() { Alumno = alumnoModel, Plan = alumno.Plan.Descripcion };
            return View(model);
        }

        // POST: AlumnoInscripcionController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult NuevaInscripcion(AlumnoInscripcionViewModel model)
        {
            model.Condicion = CondicionEnum.INSCRIPTO.ToString();
            var entity = this.mapper.Map<AlumnoInscripcion>(model);
            this.alumnoInscripcionLogic.Save(entity);
            notyf.Success($"Se ha inscripto el alumno al curso de manera existosa", 3);
            return RedirectToAction(nameof(Inscripciones), new { id = model.AlumnoId });
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult BorrarInscripcion(int inscripcionId)
        {
            var inscripcion = this.alumnoInscripcionLogic.GetOne(inscripcionId);
            this.alumnoInscripcionLogic.Borrar(inscripcionId);
            notyf.Success($"Se ha borrado la inscripción del alumno al curso de manera existosa", 3);
            return RedirectToAction(nameof(Inscripciones), new { id = inscripcion.AlumnoId });
        }
    }
}

UI.Web/Views/AlumnoInscripcion/Inscripciones.cshtml
@model AlumnoInscripcionHeadViewModel;

@{
    ViewData["Title"] = "Catedras";
}

@{
    var tuple = ("Catedras", "Plan");
}
<h2 class="display-6 text-center">Inscripciones del alumno</h2>
<div class="container">
    <div class="row">
        <div class="col-md-12 text-center text-md-left p-2">
            <a asp-controller="AlumnoInscripcion" asp-action="NuevaInscripcion" asp-route-idAlumno="@Model.AlumnoId" class="btn btn-primary">Asignar nueva inscripción</a>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-12 text-center text-md-left p-2">
            <a asp-controller="Inscripcion" asp-action="AlumnosCatedras" class="btn btn-secondary">Volver a Inscripciones de alumnos</a>
        </div>
    </div>
</div>
<div class="container">

    <table id="table" class="display responsive nowrap table table-striped" style="width:100%">
        <thead>
            <tr>
                <th>
                    Materia
                </th>
                <th>
                    Condición
                </th>
                <th class="text-center">
                    Nota
                </th>
                <th>Acciones</th>

            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.AlumnoInscripciones)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Curso.MateriaDescripcion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Condicion)
                    </td>
                    <td class="text-center">
                        @Html.DisplayFor(modelItem => item.Nota)
                    </td>
                    <td>
                        <form method="post" asp-action="BorrarInscripcion">
                            <input id="inscripcionId" name="inscripcionId" hidden value="@item.Id" />
                        </form>
                        <button id="borrar" class="btn btn-danger btn-sm">Borrar</button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<partial name="_ModalConfirmarBorrarInscripcion" />

@section scripts {
    <script>
        $(document).ready(function () {
            $('#table').DataTable({
                columnDefs: [
                    { responsivePriority: 1, targets: 0 },
                    { responsivePriority: 1, targets: 1 }
                ],
                language: {
                    "emptyTable": "No hay inscripciones registradas del alumno",
                    "search": "Buscar",
                    "paginate": {
                        "first": "Primero",
                        "last": "Último",
                        "next": "Siguiente",
                        "previous": "Anterior"
                    }
                },
                lengthChange: false,
                info: false,
            });



            $(document).on("click", "button#borrar", function () {
                formSelected = $(this).closest('tr').find('form')

                $('#modalConfirmar').modal('show');
            });

            $('#btnConfirmar').click(function () {

                formSelected.submit();
                $("#modalConfirmar").modal("dismiss");
            });
        });
    </script>
}

UI.Web/Views/AlumnoInscripcion/NuevaInscripcion.cshtml
@model AlumnoInscripcionViewModel


@{
    var accion = Model.Id == 0 ? "NuevaInscripcion" : "Editar";
}

<h3 class="text-center">Nueva inscripción</h3>
<hr />
<div class="row">
    <div class="col-md-4 col-12 col-lg-6 mx-auto">
        <form id="form" asp-action="@accion" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="mb-3 col-lg-12">
                <label asp-for="Plan" class="form-label"></label>
                <input asp-for="Plan" class="form-control form-control-md" readonly disabled style="caret-color:transparent;" />
            </div>

            <div class="mb-3 col-lg-12">

                <label asp-for="Alumno.Apellido" class="form-label"></label>
                <input asp-for="Alumno.Apellido" class="form-control form-control-md" readonly disabled style="caret-color:transparent;" />

            </div>
            <div class="mb-3 col-lg-12">
                
                    <label asp-for="Alumno.Nombre" class="form-label"></label>
                    <input asp-for="Alumno.Nombre" class="form-control form-control-md" readonly disabled style="caret-color:transparent;" />
          
            </div>
            <div class="mb-3">

                <label asp-for="Curso" class="form-label"></label>
                <div class="input-group">
                    <input id="Curso" name="Curso" readonly disabled class="form-control form-control-md" maxlength="60"  style="caret-color:transparent;" />
                    <input asp-for="AlumnoId" value="@Model.Alumno.Id" hidden />
                    <input asp-for="CursoId" hidden/>
                    <div class="input-group-append">
                        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modalCursos">
                            Seleccionar curso
                        </button>
                    </div>
                </div>
                <span asp-validation-for="@Model.CursoId" class="text-danger"></span>
            </div>
            <div class="row">
                <div class="col-md-6 col-lg-6">
                    <input type="submit" value="@accion" class="btn btn-success w-100 mb-3" />
                </div>
                <div class="col-md-6 col-lg-6">
                    <a asp-action="Inscripciones" asp-route-id="@Model.Alumno.Id" class="btn btn-danger w-100 mb-3">Cancelar</a>
                </div>

            </div>
        </form>
    </div>
</div>
<partial name="_ModalCursos" />

@section Scripts {

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
   <script>
        $(document).ready(function () {
            let cursoColumns = [
                { data: "comisionDescripcion", title: "Materia" },
                { data: "materiaDescripcion", title: "Comisión" },
                { data: "anioCalendario", title: "Año especialidad" },
                { data: "cupo", title: "Cupo" },
                    {
                    data: null, title: "Acciones",
                    render: function (data, type, full, meta) {
                        return '<button class="btn btn-primary" data-bs-dismiss="modal">Seleccionar</button>'
                    }
                }
            ]
            var tableCurso = $('#tableCurso').DataTable({
                language: {
                    "emptyTable": "No hay cursos cargados para asignar"
                },
                bAutoWidth: false,
                lengthChange: false,
                info: false,
                columns: cursoColumns
            });



            $.ajax({
                type: "GET",
                url: "/Curso/GetCursosDisponibles?idAlumno=" + @Model.Alumno.Id,
                success: function (response) {
                    tableCurso.clear().rows.add(response).draw();
                },
                error: function (error) {
                    console.log(error);
                }
            });

            $('#tableCurso tbody').on('click', 'button', function () {
                var data = tableCurso.row($(this).parents('tr')).data();
                $("#Curso").val(data.comisionDescripcion+" - "+data.materiaDescripcion);
                $("#CursoId").val(data.id);
                $("#modalComision").modal("dispose");
            });
        })
   </script>
        
}
      

UI.Web/Views/AlumnoInscripcion/_ModalConfirmarBorrarInscripcion.cshtml
<div class="modal fade" id="modalConfirmar" tabindex="-1" role="dialog" aria-labelledby="modalConfirmarLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg container-fluid" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalConfirmarLabel">Inscripción a materia</h5>
            </div>
            <div class="modal-body">
                <p>¿Desea borrar la siguiente inscripción?</p>
            </div>
            <div class="modal-footer">
                <button id="btnConfirmar" type="button" data-bs-dismiss="modal" class="btn btn-success">Aceptar</button>
                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancelar</button>
            </div>
        </div>
    </div>
</div>

UI.Web/Views/AlumnoInscripcion/_ModalCursos.cshtml
<div class="modal fade" id="modalCursos" tabindex="-1" role="dialog" aria-labelledby="cursoModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg container-fluid" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="cursoModalLabel">Seleccione un curso</h5>
            </div>
            <div class="modal-body">
                <table id="tableCurso" class="table"></table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
            </div>
        </div>
    </div>
</div>