UI.Web/Controllers/LoginController.cs
using Business.Logic;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;

namespace UI.Web.Controllers
{
    [ResponseCache(NoStore = true, Duration = 0)]
    public class LoginController : Controller
    {

        private UsuarioLogic usuarioLogic { get; set; }
        public LoginController()
        {
            this.usuarioLogic = new UsuarioLogic();
        }

        // GET: LoginController
        public ActionResult Index(string returnUrl)
        {
            TempData["url"] = returnUrl;

            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }

            return View();
        }


        public async Task<ActionResult> Loginout()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<ActionResult> Login(string nombreUsuario, string clave, string returnUrl)
        {

            try
            {
                if (ModelState.IsValid)
                {
                    var user = this.usuarioLogic.GetByCredenciales(nombreUsuario, clave);

                    var claims = new List<Claim>
                {
                    new Claim("Name", user.Nombre),
                    new Claim("Surname", user.Apellido),
                    new Claim("Email", user.Email),
                    new Claim("personaId", user.PersonaId.HasValue ? user.PersonaId.ToString() : "0"),
                    new Claim("tipoPersona", user.Persona != null ? ((int)user.Persona.TipoPersona).ToString() : "0")
                };

                    foreach (var mod in user.Modulos)
                    {
                        if (mod.Consulta)
                        {
                            claims.Add(new Claim("Modulo", $"{mod.Modulo.Descripcion}" + ".Consulta"));
                        }
                        if (mod.Alta)
                        {
                            claims.Add(new Claim("Modulo", $"{mod.Modulo.Descripcion}" + ".Alta"));
                        }
                        if (mod.Baja)
                        {
                            claims.Add(new Claim("Modulo", $"{mod.Modulo.Descripcion}" + ".Baja"));
                        }
                        if (mod.Modificacion)
                        {
                            claims.Add(new Claim("Modulo", $"{mod.Modulo.Descripcion}" + ".Modificacion"));
                        }

                    }
                    var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                    var principal = new ClaimsPrincipal(identity);
                    await HttpContext.SignInAsync(principal);
                    return Redirect("/Home");
                }
                else
                {
                    return RedirectToAction("Index");
                }

            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message;
                return RedirectToAction("Index");
            }
        }
    }
}

UI.Web/Controllers/PersonaController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using AutoMapper;
using Business.Entities;
using Business.Entities.Enums;
using Business.Logic;
using Business.Util.Exceptions;
using Microsoft.AspNetCore.Mvc;
using NuGet.Packaging.Signing;
using System;
using System.Collections.Generic;
using UI.Web.Models;

namespace UI.Web.Controllers
{
    [ResponseCache(NoStore = true, Duration = 0)]
    public class PersonaController : Controller
    {
        private IMapper _mapper;
        private INotyfService _notyfService;
        private PersonaLogic PersonaLogic => new();

        public PersonaController(IMapper mapper, INotyfService notifyService)
        {
            _mapper = mapper;
            _notyfService = notifyService;
        }

        public ActionResult Alumnos()
        {
            var vms = _mapper.Map<List<PersonaViewModel>>(PersonaLogic.GetPersonas((Business.Entities.Enums.TipoPersonaEnum)TipoPersonaEnum.ALUMNO));
            return View(vms);
        }

        public ActionResult Profesores()
        {
            var vms = _mapper.Map<List<PersonaViewModel>>(PersonaLogic.GetPersonas((Business.Entities.Enums.TipoPersonaEnum)TipoPersonaEnum.PROFESOR));
            return View(vms);
        }

        public ActionResult Administradores()
        {
            var vms = _mapper.Map<List<PersonaViewModel>>(PersonaLogic.GetPersonas((Business.Entities.Enums.TipoPersonaEnum)TipoPersonaEnum.ALUMNO));
            return View(vms);
        }

        public ActionResult Nuevo(TipoPersonaEnum tipoPersona)
        {
            var vm = new PersonaViewModel() { TipoPersona = tipoPersona };
            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Nuevo(PersonaViewModel model)
        {
            if (ModelState.IsValid)
            {
                var entity = _mapper.Map<Persona>(model);
                PersonaLogic.Save(entity);
                switch (entity.TipoPersona)
                {
                    case (Business.Entities.Enums.TipoPersonaEnum)TipoPersonaEnum.ALUMNO:
                        _notyfService.Success("Se ha creado el nuevo alumno de manera existosa", 6);
                        return RedirectToAction(nameof(Alumnos));
                    case (Business.Entities.Enums.TipoPersonaEnum)TipoPersonaEnum.PROFESOR:
                        _notyfService.Success("Se ha creado el nuevo profesor existosa", 6);
                        return RedirectToAction(nameof(Profesores));
                    default:
                        _notyfService.Success("Se ha creado el nuevo administrador existosa", 6);
                        return RedirectToAction(nameof(Administradores));
                }
            }
            else
            {
                return View();
            }

        }

        // GET: PlanController_/Edit/5
        public ActionResult Editar(int id)
        {
            var persona = PersonaLogic.GetOne(id);
            var mapped = _mapper.Map<PersonaViewModel>(persona);
            return View(mapped);
        }

        // POST: PlanController_/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(PersonaViewModel model)
        {
            if (ModelState.IsValid)
            {
                var entity = _mapper.Map<Persona>(model);
                PersonaLogic.Save(entity);
                switch (entity.TipoPersona)
                {
                    case (Business.Entities.Enums.TipoPersonaEnum)TipoPersonaEnum.ALUMNO:
                        _notyfService.Success("Se han guardado los cambios del alumno", 3);
                        return RedirectToAction(nameof(Alumnos));
                    case (Business.Entities.Enums.TipoPersonaEnum)TipoPersonaEnum.PROFESOR:
                        _notyfService.Success("Se han guardado los cambios del profesor", 3);
                        return RedirectToAction(nameof(Profesores));
                    default:
                        _notyfService.Success("Se han guardado los cambios del administrador", 3);
                        return Redirect(nameof(Administradores));
                }
            }
            else
            {
                return View(model);
            }

        }


        public JsonResult AlumnosByPlan(int idPlan)
        {
            var personas = this.PersonaLogic.AlumnosByPlan(idPlan);
            var models = this._mapper.Map<List<PersonaViewModel>>(personas);
            return Json(models);
        }


        public JsonResult PersonaByPlan(List<int> ids)
        {
            var personas = this.PersonaLogic.DocentesByPlanForCurso(ids);
            var models = this._mapper.Map<PersonaViewModel>(personas);
            return Json(models);
        }

        public ActionResult PersonaByTipoPersona(int id)
        {
            if (Enum.IsDefined(typeof(TipoPersonaEnum), id))
            {
                var valueEnum = (TipoPersonaEnum)id;
                var personas = PersonaLogic.GetPersonasForUsuarios(valueEnum);
                var models = this._mapper.Map<List<PersonaViewModel>>(personas);
                return Json(models);
            }
            else
            {
                return Json(new List<PersonaViewModel>());
            }
        }



        // GET: PlanController_/Delete/5
        public ActionResult Borrar(int id)
        {
            var entity = PersonaLogic.GetOne(id);
            var mapped = _mapper.Map<PersonaViewModel>(entity);
            return View(mapped);
        }

        // POST: PlanController_/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Borrar(PersonaViewModel personaViewModel)
        {
            try
            {
                var entity = _mapper.Map<Persona>(personaViewModel);
                PersonaLogic.Delete(entity);
                switch (entity.TipoPersona)
                {
                    case (Business.Entities.Enums.TipoPersonaEnum)TipoPersonaEnum.ALUMNO:
                        _notyfService.Success("Se ha borrado el alumno con exito", 3);
                        return RedirectToAction(nameof(Alumnos));
                    case (Business.Entities.Enums.TipoPersonaEnum)TipoPersonaEnum.PROFESOR:
                        _notyfService.Success("Se ha borrado el profesor con exito", 3);
                        return RedirectToAction(nameof(Profesores));
                    default:
                        _notyfService.Success("Se ha borrado el administrador con exito", 3);
                        return RedirectToAction(nameof(Administradores));
                }
            }
            catch (DeleteCFReferenciadaException ex)
            {
                TempData["Error"] = ex.Message;
                return RedirectToAction("Borrar", new { id = personaViewModel.Id });
            }
        }
    }
}

UI.Web/Views/Shared/Login.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

UI.Web/Views/Shared/_HeaderGeneric.cshtml
@model (string Titulo,string Entidad)
<h2 class="display-6 text-center">@Model.Titulo</h2>
    <div class="container">
    <div class="row">
        <div class="col-md-12 text-center text-md-left p-2">
            <a asp-controller="@Model.Entidad" asp-action="Nuevo" class="btn btn-primary">Crear @Model.Entidad</a>
        </div>
    </div>
</div>

UI.Web/Views/Shared/_HeaderPersona.cshtml
@using Business.Util
@model TipoPersonaEnum
    @{
    TipoPersonaEnum persona = @Model;
    string personaText = string.Empty;
    string plural = string.Empty;
    }
    @switch(Model)
    {
       case TipoPersonaEnum.ALUMNO:
            personaText = "alumno";
        plural = "Alumnos";
        break;
       case TipoPersonaEnum.PROFESOR:
            personaText = "profesor";
        plural = "Profesores";
        break;
    default:
            break;
     }

<h2 class="display-6 text-center">@plural</h2>
    <div class="container">
    <div class="row">
        <div class="col-md-12 text-center text-md-left p-2">
            <a asp-controller="Persona" asp-action="Nuevo" class="btn btn-primary" asp-route-tipopersona="@Model">Crear @personaText</a>
        </div>
    </div>
</div>

UI.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
@using Microsoft.AspNetCore.Http.Extensions;
@using Microsoft.Extensions.DependencyInjection;
@using System.Security.Claims
<!DOCTYPE html>
<html lang="en" >
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UI.Web</title>
@*     <link rel="stylesheet" href="~/css/bootstrap.min.css" /> *@
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/DataTables/datatables.min.css">
    <style>

    </style>
    <script>

    </script>
</head>

@{
    string basePath = Context.Request.PathBase;
    string path = Context.Request.Path;

    // Combina basePath y path para obtener la URL sin localhost
    string urlWithoutHost = basePath + path;
}


<body style="background-color:#6495ED">

    @if (User.Identity.IsAuthenticated)
    {
        <partial name="_navbarAdmin" />
    }





    <div class="container" >
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script type="text/javascript" src="https://code.jquery.com/jquery-3.7.1.js"></script>
    <script src="~/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>

    <script src="~/DataTables/datatables.min.js"></script>
    @await Component.InvokeAsync("Notyf")
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

UI.Web/Views/Shared/_LayoutAlumno.cshtml
@using Microsoft.AspNetCore.Http;
@using Microsoft.AspNetCore.Http.Extensions;
@using Microsoft.Extensions.DependencyInjection;
@using System.Security.Claims
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UI.Web</title>
    @*     <link rel="stylesheet" href="~/css/bootstrap.min.css" /> *@
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/DataTables/datatables.min.css">
    <style>

    </style>
</head>

@{
    string basePath = Context.Request.PathBase;
    string path = Context.Request.Path;

    // Combina basePath y path para obtener la URL sin localhost
    string urlWithoutHost = basePath + path;
}


<body style="background-color:#6495ED">
    <partial name="_navbarAlumno" />




    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="col-md-12 col-lg-12 col-sm-12">
        <div class="container" style="color: white">
            &copy; 2022 - UTN Frro - Academia
        </div>
    </footer>


    <script type="text/javascript" src="https://code.jquery.com/jquery-3.7.1.js"></script>
    <script src="~/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>

    <script src="~/DataTables/datatables.min.js"></script>
    @await Component.InvokeAsync("Notyf")
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

UI.Web/Views/Shared/_LayoutProfesor.cshtml
@using Microsoft.AspNetCore.Http;
@using Microsoft.AspNetCore.Http.Extensions;
@using Microsoft.Extensions.DependencyInjection;
@using System.Security.Claims
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UI.Web</title>
    @*     <link rel="stylesheet" href="~/css/bootstrap.min.css" /> *@
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/DataTables/datatables.min.css">
    <style>

    </style>
</head>

@{
    string basePath = Context.Request.PathBase;
    string path = Context.Request.Path;

    // Combina basePath y path para obtener la URL sin localhost
    string urlWithoutHost = basePath + path;
}


<body style="background-color:#6495ED">
    <partial name="_navbarProfesor" />




    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*     <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>

    *@

    <script type="text/javascript" src="https://code.jquery.com/jquery-3.7.1.js"></script>
    <script src="~/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>

    <script src="~/DataTables/datatables.min.js"></script>
    @await Component.InvokeAsync("Notyf")
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

UI.Web/Views/Shared/_layoutAdmin.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

UI.Web/Views/Shared/_navbarAdmin.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar navbar-dark bg-dark border-bottom box-shadow mb-3">
    <div class="container">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Academia</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between" id="navbarTogglerDemo02">
            <ul class="navbar-nav flex-grow-1">

                <li class="nav-item dropdown">
                </li>
            </ul>
            <span class="navbar-text">

                @if (User.Identity.IsAuthenticated)
                {
                    var nombre = User.Claims.FirstOrDefault(x => x.Type == "Name").Value;
                    var surname = User.Claims.FirstOrDefault(x => x.Type == "Surname").Value;
                    @string.Format("{0} {1}", nombre, surname)
                    <a asp-controller="Login" asp-action="Loginout">Salir</a>
                }


            </span>
        </div>
    </div>
</nav>

UI.Web/Views/Shared/_navbarAlumno.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar navbar-dark bg-dark border-bottom box-shadow mb-3">
    <div class="container">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Academia</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between" id="navbarTogglerDemo02">
            <ul class="navbar-nav flex-grow-1">
                @if (User.HasClaim("tipoPersona", "2"))
                {
                    <li><a class="nav-item dropdown-item" asp-area="" asp-controller="Inscripcion" asp-action="MisCatedras">Inscripciones</a></li>

                }
                else
                {
                    <li><a class="nav-item dropdown-item" asp-area="" asp-controller="Inscripcion" asp-action="AlumnosCatedras">Inscripciones</a></li>
                }
            </ul>
            <span class="navbar-text">

                @if (User.Identity.IsAuthenticated)
                {
                    var nombre = User.Claims.FirstOrDefault(x => x.Type == "Name").Value;
                    var surname = User.Claims.FirstOrDefault(x => x.Type == "Surname").Value;
                    @string.Format("{0} {1}", nombre, surname)

                    <a asp-controller="Login" asp-action="Loginout">Salir</a>
                }



            </span>
        </div>
    </div>
</nav>

UI.Web/Views/Shared/_navbarProfesor.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar navbar-dark bg-dark border-bottom box-shadow mb-3">
    <div class="container">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Academia</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between" id="navbarTogglerDemo02">
            <ul class="navbar-nav flex-grow-1">

                <li class="nav-item dropdown">
                </li>
            </ul>
            <span class="navbar-text">

                @if (User.Identity.IsAuthenticated)
                {
                    var nombre = User.Claims.FirstOrDefault(x => x.Type == "Name").Value;
                    var surname = User.Claims.FirstOrDefault(x => x.Type == "Surname").Value;
                    @string.Format("{0} {1}", nombre, surname);
                    <a asp-controller="Login" asp-action="Loginout">Salir</a>
                }


            </span>
        </div>
    </div>
</nav>